### ISSUE TITLE
Angular 18 config example request

### ISSUE THREAD

**Issue by jonmarozick** [anolilab/unplugin-favicons#44]
I'm trying to use this package to generate favicons in an Angular 18 application. I'm using the [@angular-builders/custom-esbuild:application](https://www.npmjs.com/package/@angular-builders/custom-esbuild?activeTab=readme) builder so I can add plugins into the esbuild system. I've looked at their [examples ](https://github.com/just-jeb/angular-builders/tree/master/examples/custom-esbuild)but have had no luck.

The message I get is: An unhandled exception occurred: Package subpath './esbuild' is not defined by "exports" in C:\Projects\a18\esbuildtest\node_modules\@anolilab\unplugin-favicons\package.json

[Here is a Stackblitz](https://stackblitz.com/edit/stackblitz-starters-lc9upn?file=angular.json) that shows the issue. Please forgive me if I've missed something simple.

Thanks.

**Comment by prisis** [comment]
Hey, sorry missing this notification, i will take a look asap

**Comment by prisis** [comment]
Hey @jonmarozick, added a example for angular without ts use of the esbuild, didnt find a example in the "@angular-builders/custom-esbuild" you can find it on -> 

https://github.com/anolilab/unplugin-favicons/tree/main/examples/angular

**Comment by jonmarozick** [comment]
Thanks that worked!

**Comment by prisis** [comment]
Currently not, should switch it maybe to debug
