### ISSUE TITLE
svelte preprocessor for sveltekit support

### ISSUE THREAD

**Issue by ryoppippi** [anolilab/unplugin-favicons#45]
### Clear and concise description of the problem

For now, this plugin does not support sveltekit because vite transforrmation is not applied to sveltekit build result.

### Suggested solution

Create svelte preprocessor to modify `<head>` ta

**Comment by prisis** [comment]
Hey @ryoppippi, could you provide me more infos (like docs, api or a how to do it), i didnt work with svelte before.

**Comment by ryoppippi** [comment]
@prisis 
Hi.
I'm considering and found that svelte preprocessor is not appropriate way.
If we have some way to import header text add it to head tag using hooks(https://kit.svelte.dev/docs/hooks), that's fine

**Comment by ryoppippi** [comment]
It is the same idea with  #2

**Comment by ryoppippi** [comment]
close this issue because it looks duplicated of #2
