### ISSUE TITLE
Nuxt configKey is wrong, error on run, and doesn't run on dev process

### ISSUE THREAD

**Issue by gridsystem** [anolilab/unplugin-favicons#50]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/anolilab/unplugin-favicons/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/anolilab/unplugin-favicons/blob/main/.github/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/anolilab/unplugin-favicons/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a unplugin-favicons issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anolilab/unplugin-favicons/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

1) your [Nuxt module configKey](https://nuxt.com/docs/api/kit/modules#parameters) [is set to `openapi-jsdoc-compiler`](https://github.com/anolilab/unplugin-favicons/blob/a90d778dfcca5c326ff09ef8ade4823e432d3085/src/nuxt.ts#L13) instead of `faviconsPlugin` which you've used for other frameworks/builders. See the [Nuxt Google Fonts module](https://google-fonts.nuxtjs.org/getting-started/setup#options) for an example of Nuxt's two different config formats, one of which uses this configKey as a key.

2) When using this config, and running `pnpm build`, I get the error `ERROR  Nuxt Build Error: [@anolilab/unplugin-favicons] The "path" argument must be of type string or an instance of Buffer or URL. Received undefined`

```
'openapi-jsdoc-compiler': {
	logo: '/assets/logo.svg', // or png produces the same error
	appName: 'redacted',
	developerName: 'redacted',
	developerURL: 'redacted',
	background: '#bada55',
	theme_color: '#c0ff33',
	icons: {
		windows: false,
		yandex: false
	}
}
```

3) Nothing happens at all when running `pnpm dev`, which is the local development server. It would be nice if the module worked with this to preview the results during the standard dev process instead of `pnpm build` which is the production build process.

I'm sorry I haven't followed the bug report format, I'm working on a project and have limited time. This looks like a great project though and you should submit it to the Nuxt modules directory!

As an aside, `unplugFavicon` would make a great module name instead of the more generic `faviconsPlugin`.

### Environment Info

```shell
sh: envinfo: command not found
```

### Which module system do you use?

- [ ] CJS
- [ ] ESM

### Used Package Manager

pnpm

**Comment by prisis** [comment]
Hey @gridsystem, thank you for the bug report :)

Point 1 and 2 are fixed in https://github.com/anolilab/unplugin-favicons/pull/51

For point 3, need a bit more time to find a good way to do it

**Comment by prisis** [comment]
version 1.0.4 will have a working nuxt intigration :)
