### ISSUE TITLE
No HTML injection with Astro

### ISSUE THREAD

**Issue by openscript** [anolilab/unplugin-favicons#54]
### Pre-Checks

- [X] Follow our [Code of Conduct](https://github.com/anolilab/unplugin-favicons/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/anolilab/unplugin-favicons/blob/main/.github/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/anolilab/unplugin-favicons/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a unplugin-favicons issue and not related to a combination with another package.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anolilab/unplugin-favicons/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [ ] I am willing to provide a PR.

### Describe the bug

I'm trying to use this inside an Astro project. Unfortunately I never succeeded that the HTML got injected. My `astro.config.mjs`:

```js
import { defineConfig } from 'astro/config';
import unpluginFavicons from '@anolilab/unplugin-favicons/vite';

// https://astro.build/config
export default defineConfig({
  vite: {
    plugins: [
      unpluginFavicons({
        logo: 'res/brand/icon.png',
        inject: true,
      }),
    ],
  },
});
```

I've also tried to use the default config and put the logo to `assets/logo.png`. That didn't work as well.

### Minimal reproduction code

https://stackblitz.com/edit/github-9xnszu?file=astro.config.mjs

### Additional Context

https://github.com/user-attachments/assets/0c8848ce-9e4d-4c96-9492-9d89d774c97f

Additionally I get this warnings:

20:10:40 [WARN] [vite] plugin '@anolilab/unplugin-favicons' uses deprecated 'enforce' option. Use 'order' option instead.
20:10:40 [WARN] [vite] plugin '@anolilab/unplugin-favicons' uses deprecated 'transform' option. Use 'handler' option instead.

### Environment Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
```

### Which module system do you use?

- [ ] CJS
- [X] ESM

### Used Package Manager

pnpm

**Comment by prisis** [comment]
Hey @openscript could you test 1.0.5-alpha.2, this version should fixed the issue

**Comment by openscript** [comment]
Hallo @prisis 
Thank you for the quick reaction. You fixed the issue and the warnings as well!
I've updated https://stackblitz.com/edit/github-9xnszu
:partying_face:

**Comment by prisis** [comment]
Nice, I updated the example too, will make a new release soon
