### ISSUE TITLE
can't create a folder for favicons inside dist

### ISSUE THREAD

**Issue by saiballo** [anolilab/unplugin-favicons#68]
Hello,

how can i create a folder inside folder "dist" for all favicons? now are created in the root of "dist"

thank you

**Comment by saiballo** [comment]
the solution is to use " outputPath" but this option is not documented. 

On https://github.com/itgalaxy/favicons#usage is mentioned "path" option.

**Comment by prisis** [comment]
Hey @saiballo

Sorry for the late response 

Would you like to make a PR to add it to the docs?
